# Generated by Django 5.0.6 on 2024-06-06 13:15

from django.db import migrations
from django.contrib.auth.models import Group

def apply_migration(apps, schema_editor):
    Group.objects.bulk_create([
        Group(name=u'export'),
        Group(name=u'read'),
    ])


def revert_migration(apps, schema_editor):
    Group.objects.filter(
        name__in=[
            u'export',
            u'read'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
