# Generated by Django 5.0.6 on 2024-06-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cellularsubscription', models.FloatField()),
                ('internetuserspercent', models.FloatField()),
                ('internetusersnumber', models.IntegerField()),
                ('broadbandsubscription', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.country')),
            ],
            options={
                'db_table': 'internet',
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.country')),
            ],
            options={
                'db_table': 'population',
            },
        ),
        migrations.CreateModel(
            name='Unemployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.country')),
            ],
            options={
                'db_table': 'unemployment',
            },
        ),
    ]
