--
-- PostgreSQL database dump
--

-- Dumped from database version 15.5 (Ubuntu 15.5-1.pgdg20.04+1)
-- Dumped by pg_dump version 15.5 (Ubuntu 15.5-1.pgdg20.04+1)
create database projekt_integracja with owner projekt_integracja;
\c projekt_integracja;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: main; Type: SCHEMA; Schema: -; Owner: projekt_integracja
--

CREATE SCHEMA main;


ALTER SCHEMA main OWNER TO projekt_integracja;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE main.auth_group OWNER TO projekt_integracja;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE main.auth_group_permissions OWNER TO projekt_integracja;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE main.auth_permission OWNER TO projekt_integracja;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE main.auth_user OWNER TO projekt_integracja;

--
-- Name: auth_user_groups; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE main.auth_user_groups OWNER TO projekt_integracja;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE main.auth_user_user_permissions OWNER TO projekt_integracja;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE main.authtoken_token OWNER TO projekt_integracja;

--
-- Name: country; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.country (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    code character varying(10) NOT NULL
);


ALTER TABLE main.country OWNER TO projekt_integracja;

--
-- Name: country_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

CREATE SEQUENCE main.country_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE main.country_id_seq OWNER TO projekt_integracja;

--
-- Name: country_id_seq; Type: SEQUENCE OWNED BY; Schema: main; Owner: projekt_integracja
--

ALTER SEQUENCE main.country_id_seq OWNED BY main.country.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE main.django_admin_log OWNER TO projekt_integracja;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE main.django_content_type OWNER TO projekt_integracja;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE main.django_migrations OWNER TO projekt_integracja;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

ALTER TABLE main.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE main.django_session OWNER TO projekt_integracja;

--
-- Name: internet; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.internet (
    id integer NOT NULL,
    country_id integer NOT NULL,
    year integer NOT NULL,
    cellularsubscription double precision NOT NULL,
    internetuserspercent double precision NOT NULL,
    internetusersnumber integer NOT NULL,
    broadbandsubscription double precision NOT NULL
);


ALTER TABLE main.internet OWNER TO projekt_integracja;

--
-- Name: internet_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

CREATE SEQUENCE main.internet_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE main.internet_id_seq OWNER TO projekt_integracja;

--
-- Name: internet_id_seq; Type: SEQUENCE OWNED BY; Schema: main; Owner: projekt_integracja
--

ALTER SEQUENCE main.internet_id_seq OWNED BY main.internet.id;


--
-- Name: population; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.population (
    id integer NOT NULL,
    year integer NOT NULL,
    value bigint,
    country_id integer NOT NULL
);


ALTER TABLE main.population OWNER TO projekt_integracja;

--
-- Name: population_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

CREATE SEQUENCE main.population_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE main.population_id_seq OWNER TO projekt_integracja;

--
-- Name: population_id_seq; Type: SEQUENCE OWNED BY; Schema: main; Owner: projekt_integracja
--

ALTER SEQUENCE main.population_id_seq OWNED BY main.population.id;


--
-- Name: unemployment; Type: TABLE; Schema: main; Owner: projekt_integracja
--

CREATE TABLE main.unemployment (
    id integer NOT NULL,
    year integer NOT NULL,
    value numeric(6,3),
    country_id integer NOT NULL
);


ALTER TABLE main.unemployment OWNER TO projekt_integracja;

--
-- Name: unemployment_id_seq; Type: SEQUENCE; Schema: main; Owner: projekt_integracja
--

CREATE SEQUENCE main.unemployment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE main.unemployment_id_seq OWNER TO projekt_integracja;

--
-- Name: unemployment_id_seq; Type: SEQUENCE OWNED BY; Schema: main; Owner: projekt_integracja
--

ALTER SEQUENCE main.unemployment_id_seq OWNED BY main.unemployment.id;


--
-- Name: country id; Type: DEFAULT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.country ALTER COLUMN id SET DEFAULT nextval('main.country_id_seq'::regclass);


--
-- Name: internet id; Type: DEFAULT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.internet ALTER COLUMN id SET DEFAULT nextval('main.internet_id_seq'::regclass);


--
-- Name: population id; Type: DEFAULT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.population ALTER COLUMN id SET DEFAULT nextval('main.population_id_seq'::regclass);


--
-- Name: unemployment id; Type: DEFAULT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.unemployment ALTER COLUMN id SET DEFAULT nextval('main.unemployment_id_seq'::regclass);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: country country_code_key; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.country
    ADD CONSTRAINT country_code_key UNIQUE (code);


--
-- Name: country country_name_key; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.country
    ADD CONSTRAINT country_name_key UNIQUE (name);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: internet internet_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.internet
    ADD CONSTRAINT internet_pkey PRIMARY KEY (id);


--
-- Name: population population_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.population
    ADD CONSTRAINT population_pkey PRIMARY KEY (id);


--
-- Name: unemployment unemployment_pkey; Type: CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.unemployment
    ADD CONSTRAINT unemployment_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_group_name_a6ea08ec_like ON main.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON main.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON main.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON main.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_user_groups_group_id_97559544 ON main.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON main.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON main.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON main.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX auth_user_username_6821ab7c_like ON main.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON main.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON main.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON main.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX django_session_expire_date_a5c62663 ON main.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: main; Owner: projekt_integracja
--

CREATE INDEX django_session_session_key_c0390e0f_like ON main.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES main.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES main.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES main.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES main.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES main.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES main.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES main.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES main.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES main.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES main.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: internet internet_country_fk; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.internet
    ADD CONSTRAINT internet_country_fk FOREIGN KEY (country_id) REFERENCES main.country(id);


--
-- Name: population population_country_fk; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.population
    ADD CONSTRAINT population_country_fk FOREIGN KEY (country_id) REFERENCES main.country(id);


--
-- Name: unemployment unemployment_country_fk; Type: FK CONSTRAINT; Schema: main; Owner: projekt_integracja
--

ALTER TABLE ONLY main.unemployment
    ADD CONSTRAINT unemployment_country_fk FOREIGN KEY (country_id) REFERENCES main.country(id);


--
-- PostgreSQL database dump complete
--

